# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "XJTU AI Research"
title:              "XJTU AI Research"
description:        "The XJTU AI Research Network is a platform for Xi'an Jiaotong University students to connect, share, and collaborate in the field of artificial intelligence."


# URL
url:                https://xjtuai.com
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "news"
    href:           "/news"
  # - name:           "research"
  #   href:           "/research"
  # - name:           "publications"
  #   href:           "/publication"
  - name:           "people"
    href:           "/people"
#  - name:           "blog"
#    href:           "/blog"
#  - name:           "resources"
#    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  members:
    output: true
    permalink: /people/:title/index.html
